# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Fetch - Remastered' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Google-Mobile-Ads-SDK'
  # Pods for Fetch - Remastered

end

target 'Fetch - Remastered Stickers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fetch - Remastered Stickers

end
